### ISSUE TITLE
Landmarks definition - registering two images without any other input

### ISSUE THREAD

**Issue by asmagen** [Borda/BIRL#46]
I don't understand how do I register a pair of images without any landmarks? Do I have to define landmark to register? How do I do that (not manually)?
I'm trying to develop a fully automated pipeline so I hope I can provide just a set of png files and get an output of png aligned to the first image.

**Comment by Borda** [comment]
you can use any of these SOTA methods listed in this benchmark - https://github.com/Borda/BIRL/tree/master/bm_experiments
For an image registration survey, you may read http://library.utia.cas.cz/prace/20030125.pdf

> I don't understand how do I register a pair of images without any landmarks?

You are minimising a similarity measure based on image intensity

> Do I have to define landmark to register? How do I do that (not manually)?

You can determine your own landmarks e.g. with SIFT

**Comment by asmagen** [comment]
Thanks but can you clarify which of these doesn't require landmarks and scales well to whole slide pathology images with scaling and non linear warping?

**Comment by Borda** [comment]
all of them requires only images as input, that is the whole point of image registration, because if you have already landmarks/key points you know the transformation and there is nothing to do
Depends what is the image size of your WSI, we have tested up to 20k image size, see robustness in [BIRL: Benchmark on Image Registration methods with Landmark validation](https://www.researchgate.net/publication/338291737_BIRL_Benchmark_on_Image_Registration_methods_with_Landmark_validation)
